version: "3.5"
services:
  haproxy:
    image: haproxytech/haproxy-alpine:latest
    container_name: haproxy
    restart: on-failure
    ports:
      - ${PROXY_PORT:-80}:80
    networks:
      - default
    profiles:
      - stacks-blockchain
    volumes:
      - ${SCRIPTPATH}/conf/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - stacks-blockchain-api
