version: "3.5"
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    shm_size: ${PG_SHMSIZE:-256MB}
    container_name: postgres
    restart: on-failure
    env_file:
      - ${SCRIPTPATH}/.env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ${SCRIPTPATH}/scripts/postgres-initdb.sh:/docker-entrypoint-initdb.d/postgres-initdb.sh
    # ports:
    #   - ${PG_PORT:-5432}:5432
    networks:
      - default
    profiles:
      - event-replay
      - stacks-blockchain
  stacks-blockchain-api:
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=postgres
      - PG_SCHEMA=public
    depends_on:
      - postgres
